### ISSUE TITLE
Missing configuration files for Wifi and Preferences

### ISSUE THREAD

**Issue by D-G-L** [cyberwisk/M5Cardputer_WebRadio#4]
Hello, first thank you for your work. But without a adjustable preferences.h (and with that, wifi configuration) it does not work.
The webradio works well with extended user Demo, but there you can not change WiFi Parameters constantly or adjust Radio streams for your own needs.
So, pls provide a proper preferences.h for the cardputer

**Comment by D-G-L** [comment]
The Bin File is working perfectly. Could you specify a raw preferences.h - File, Preferences is NOT a library, and the related link does not give an example how to create a fitting one for webradio. Tks in advance

**Comment by cyberwisk** [comment]
Verifique a nova versão
