### ISSUE TITLE
Bluetooth Connection to external Speaker

### ISSUE THREAD

**Issue by D-G-L** [cyberwisk/M5Cardputer_WebRadio#5]
Working quite well, it would be fantastic to have a Bluetooth Connection to an external Device/Bluetooth Speaker. There are so many cheapp Bluetooth Devices that will bring a much better sound for the Cardputer. The internal speaker is not quite the fruit of the loom. The Web Radio Application is one of the few Programs that make sense!

**Comment by cyberwisk** [comment]
Sua ideia é muito boa, mas esse é um projeto de final de semana não tenho tempo sobrando, ficaria muito feliz se você colaborasse com o projeto.

**Comment by cyberwisk** [comment]
, é possível conectar um fone de ouvido Bluetooth ao ESP32-S3 para reproduzir áudio. No entanto, o ESP32-S3 não suporta nativamente a funcionalidade de saída de áudio por Bluetooth. Você precisaria de um módulo adicional ou uma placa que suporte a funcionalidade de saída de áudio Bluetooth, como o ESP32-A2DP.
